service: budget-notifier

provider:
  name: aws
  runtime: python3.7
  iamManagedPolicies:
    - 'arn:aws:iam::192266911060:policy/lambda_budget_tracker_notifier'

package:
  individually: true
  exclude:
    - ./**

functions:
  budget_notifier:
    handler: budget_notifier.budget_notifier
    events:
      - schedule: cron(0 13 * * ? *)
      - http:
          path: budget_test
          method: get
    package:
      include:
       - requirements.txt
       - budget_notifier.py

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
